name: flunt_dart
description: Library that provides a fluent way to use Notification Pattern.
version: 0.2.0
homepage: https://github.com/PedroBissonho/flunt-dart
author: Pedro Bissonho <pedro.bissonho@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  test_coverage: ^0.3.0+1